# Swagger UI Configuration
springfox.documentation.enabled=true
springfox.documentation.swagger-ui.enabled=true

#Spring JPA configurations
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#H2 Console access - http://localhost:8080/h2-console
spring.h2.console.enabled=true


aws.region=test
secretmanager.key=test
cognito.userpool.id=test
sns.arn=test